<a href="https://colab.research.google.com/github/Shubham81155/data-science3sem/blob/main/datascienceclasses.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("HELLO WORLD")

HELLO WORLD


In [ ]:
a=int(input())
b=int(input())
print("The product of a*b is",a*b)

3
3
The product of a*b is 9


In [ ]:
a=int(input("enter The numbeer"))
if(a<0):
  a=-a
print("The abs value of a given number is",a)


enter the numbeer-9
the abs value of a given number is 9


In [ ]:
a=int(input("Enter The number"))
if a%2==0:
  print("The number is even")
if a%2!=0:
  print("The number is odd")

Enter the number3
the number is odd


#smallest number

In [ ]:
p=int(input())
q=int(input())
if(p<q):
  print(p,"is smallest number")
else:
  print(q,"is smallest number")

4
5
4 is smallest number


**wap to accept three subject marks and find The studentis pass or fail?**

In [ ]:
s1=int(input("Enter The first subject"))
s2=int(input("Enter The Second subject"))
s3=int(input("Enter The Third subject"))
if s1>=35 and s2>=35 and s3>=35:
  print("The student is pass ")
else:
  print("The student is fail")

Enter the first subject45
Enter the Second subject56
Enter the Third subject67
The student is pass 


**wap to find The biggest numbeer among The given  two numbers?**


In [ ]:
a=int(input("Enter The first "))
b=int(input("Enter The Second "))
c=int(input("Enter The Third "))
if a>b:
  if a>c:
    print(a,"is greater")
  else:
    print(c,"is greater")
else:
  if b>c:
    print(b,"is greater")
  else:
    print(c,"is greater")

Enter the first 4
Enter the Second 4
Enter the Third 4
4 is greater


**wap to find The given number is in The range of 1 to 10 or 11 to 20 or 21 to 30 or 31 to 40 or greater than 40.**


In [ ]:
n=int(input("Enter number"))
if n>=1 and n<=10:
  print("The given number is in The range of 1 to 10")
elif n>=11 and n<=20:
  print("The given number is in The range of 11 to 20")
elif n>=21 and n<=30:
  print("The given number is in The range of 21 to 30")
elif n>=31 and n<=40:
  print("The given number is in The range of 31 to 40")
else:
  print("The given  number is greater than 40")

Enter number34
The given number is in The range of 31 to 40


**wap to find the given person is eligible for vote or not?**


In [ ]:
age=int(input("Enter the age:"))
if age>=18:
  print("The pertson is eligible for vote")
else:
   print("The pertson is not eligible for vote")

Enter the age:12
The pertson is not eligible for vote


**wap to accept two inputs  one is person name and second is gender.
If the gender is male print welcome to mr. name or female print welcome to ms name**

In [ ]:
name=input("Enter the name ")
gender=input("Enter the gender ")
if gender=="male":
  print("Welcome mr.",name)
else:
  print("Welcome ms.",name)

Enter the name shubham
Enter the gender male
Welcome mr. shubham


**WHILE Loop**

In [ ]:
i=0
while (i<11):
  print("HELLO WORLD")
  i+=1


HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD


**FOR Loop**

In [ ]:
for i in range(0,11,1):
  print("HELLO WORLD")

HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD
HELLO WORLD


In [ ]:
#SEQUENCE OF CHARACTER
for i in "python":
 print(i)

p
y
t
h
o
n


**Function**

In [ ]:
#function without arguments
def greet():
  print("HELLO WORLD")
greet()

HELLO WORLD


In [ ]:
#function with Argument
def sum(a,b):
  c=a+b
  print(c)
sum(10,20)

30


In [ ]:
#function with return statement
def sum(a,b):
  c=a+b
  return c
print(sum(10,20)+30)

60


In [ ]:
#function with Argument
def sum(a,b):
  c=a+b
  #print(c)
print(sum(10,20))

None


**DATA COLLECTION**  :-
**LIST /  TUPLE/ SET/ DICTIONARY **
**IT CONTAIN MULTIPLE DATA TYPES**

In [ ]:
l=[0,20,30,"HELLO WORLD"]
print(type(l))
print(l)
c=[]
c=list()
c.append("Apple")
print(c)
c.extend(["Banana","mango"])
print(c)
c.insert(1,"Orange")
print(c)

print(c[0:2])
#c.remove("Banana")
#c.pop(1)
#del c[3]

#Len,index,min,max,sum,count
count =len(c)
print(count)



<class 'list'>
[0, 20, 30, 'HELLO WORLD']
['Apple']
['Apple', 'Banana', 'mango']
['Apple', 'Orange', 'Banana', 'mango']
['Apple', 'Orange']
4


**Number is prime or composite**


In [ ]:
n=int(input("Enter the number:"))
is_prime = False
for i in range(2,n):
  if(i % n==0):
    is_prime = False
    break
  else:
      is_prime=True
if is_prime:
   print("The given number is Prime")
else:
   print("The given number is Composite")




Enter the number:5
The given number is Prime


**COMPREHENSION**

In [ ]:
#EXPRESSION FOR ITEM IN ITERABLE
l = [x**2 for x in range(1, 100)]
print(l)
l = [x for x in range(0, 100) if x % 2 == 0]
print(l)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


**even prime number**

In [ ]:
for num in range(2,100):
  is_prime = False
  for i in range(2,num):
    if(num % i==0):
      is_prime = False
      break
    else:
      is_prime=True
  if is_prime:
    print(num," given number is Prime")
  else:
    print(num," given number is Composite")

2  given number is Composite
3  given number is Prime
4  given number is Composite
5  given number is Prime
6  given number is Composite
7  given number is Prime
8  given number is Composite
9  given number is Composite
10  given number is Composite
11  given number is Prime
12  given number is Composite
13  given number is Prime
14  given number is Composite
15  given number is Composite
16  given number is Composite
17  given number is Prime
18  given number is Composite
19  given number is Prime
20  given number is Composite
21  given number is Composite
22  given number is Composite
23  given number is Prime
24  given number is Composite
25  given number is Composite
26  given number is Composite
27  given number is Composite
28  given number is Composite
29  given number is Prime
30  given number is Composite
31  given number is Prime
32  given number is Composite
33  given number is Composite
34  given number is Composite
35  given number is Composite
36  given number is Composit

In [ ]:
l=[1,2,3,4,5,6,7,8,9]
#sequence of character
for i in l:
  print("Character",i)
#sequence of numbers
for i in range(1,len(l)):
  print("Index",l[i])

Character 1
Character 2
Character 3
Character 4
Character 5
Character 6
Character 7
Character 8
Character 9
Index 2
Index 3
Index 4
Index 5
Index 6
Index 7
Index 8
Index 9


**print 1 to 10 natural number**

In [ ]:
i =1
while i<=10:
  print(i," ")
  i = i+1

1  
2  
3  
4  
5  
6  
7  
8  
9  
10  


**Tuple**

In [ ]:
t1 = (5,4,3,2,1)
sum=0
for k in t1:
  print(k)
  sum = sum+k
print("The sum of the tuple elements is",sum)

5
4
3
2
1
The sum of the tuple elements is 15


**LIST**

In [ ]:
l1=[5,4,3,2,1]

print(l1)
#For loop
for i in range(len(l1)):
  print(l1[i],end=" ")
  #FOR EACH LOOP
l1.append(10)
l1.append(20)
l1.remove(5)
del l1[1]
print()
for k in l1:
  print(k)

[5, 4, 3, 2, 1]
5 4 3 2 1 
4
2
1
10
20


In [ ]:
n = int(input("Enter the number of stars"))
for i in range(n):
  print(i* " **")


Enter the number of stars4

 **
 ** **
 ** ** **


 **SET**

In [ ]:
s1={5,4,3,2,6,78,8,9}
print(s1)
s1.add(55)
s1.remove(5)
print(s1)
for k in s1:
  print(k)



{2, 3, 4, 5, 6, 8, 9, 78}
{2, 3, 4, 6, 8, 9, 78, 55}
2
3
4
6
8
9
78
55


**DICTIONARY**

In [ ]:
d1={}
d2={1:"ram",2:"mahesh",3:"Prabhas",4:"Arjun",5:"Divya"}
print(d2[5])
print(d2)
d2[6]= "Shubham"
d2[4]="Abhay"
del d2[1]
for k in d2.keys():
  print(k,"--->",d2[k])

Divya
{1: 'ram', 2: 'mahesh', 3: 'Prabhas', 4: 'Arjun', 5: 'Divya'}
2 ---> mahesh
3 ---> Prabhas
4 ---> Abhay
5 ---> Divya
6 ---> Shubham


**square pattern**

In [ ]:
n = int(input("Enter the number of stars"))
for i in range(n):
  for i in range(n):
    print("[ ]",end=" ")
print()

Enter the number of stars4
[ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] [ ] 


**SPLIT FUNCTION()**

In [ ]:
import re
r1=re.compile(r'\W+')
t1="Welcome to data science"
print(r1.split(t1))
res=r1.split(t1)

print(res)
print(r1.split(t1,2))

['Welcome', 'to', 'data', 'science']
['Welcome', 'to', 'data', 'science']
['Welcome', 'to', 'data science']


**NUMPY**

In [ ]:
#random number generation
import numpy as np
a= np.random.rand(4)
a

array([0.58985529, 0.6156124 , 0.28408411, 0.02877091])

In [ ]:
a=np.random.rand(4)*6
a

array([0.92342143, 3.9896814 , 2.61778438, 2.38347147])

**DATA TYPE**


In [ ]:
a= np.arange(100)
print(a)
a.dtype

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


dtype('int64')

In [ ]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
a[1,1]

2

In [ ]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**Slicing**

In [ ]:
a=np.arange(50)
a



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
a[2:11:2]

array([ 2,  4,  6,  8, 10])

In [ ]:
a[3:40:3]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [ ]:
a=np.arange(1000)
a[500:]=10
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
a[0:51]=100
a

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

**Copies and views**

In [ ]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [ ]:
c=a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [ ]:
c[0]=10
c

array([10,  2,  4,  6,  8])

In [ ]:
a=np.array([1,2,3,4,5,6])
a+1

array([2, 3, 4, 5, 6, 7])

In [ ]:
a ** 2

array([ 1,  4,  9, 16, 25, 36])

In [ ]:
b=np.ones(6)+1
print(b)

a * b


[2. 2. 2. 2. 2. 2.]


array([ 2.,  4.,  6.,  8., 10., 12.])

In [ ]:
a - b


array([-1.,  0.,  1.,  2.,  3.,  4.])

In [ ]:

a + b

array([3., 4., 5., 6., 7., 8.])

**Matrix multiplication**

In [ ]:
c=np.diag([1,2,3,4])
print(c)
print(c*c)
print(c.dot(c))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


**PANDAS**





In [46]:
import pandas as pd
td ={'Ram':[78,76,89],'Ravi':[67,87,65],'Shubham':[56,98,89]}
df =pd.DataFrame(td)
df

Ram  Ravi  Shubham
0   78    67       56
1   76    87       98
2   89    65       89

In [47]:
df = df.T
df

0   1   2
Ram      78  76  89
Ravi     67  87  65
Shubham  56  98  89

In [48]:
df .columns=['Quiz_1','Quiz_2','Quiz_3']
df

Quiz_1  Quiz_2  Quiz_3
Ram          78      76      89
Ravi         67      87      65
Shubham      56      98      89

In [49]:
#accessing first row by index number
df.iloc[0]


Quiz_1    78
Quiz_2    76
Quiz_3    89
Name: Ram, dtype: int64

In [50]:
df.iloc[1]

Quiz_1    67
Quiz_2    87
Quiz_3    65
Name: Ravi, dtype: int64

In [51]:
df.iloc[1,0:3]

Quiz_1    67
Quiz_2    87
Quiz_3    65
Name: Ravi, dtype: int64

In [23]:
df.iloc[1,0:2]

Quiz_1    67
Quiz_2    87
Name: Ravi, dtype: int64

In [52]:
df.iloc[1,1:3]

Quiz_2    87
Quiz_3    65
Name: Ravi, dtype: int64

In [26]:
df.iloc[1,1:2]

Quiz_2    87
Name: Ravi, dtype: int64

In [53]:
#accessing the first column by name
df['Quiz_1']

Ram        78
Ravi       67
Shubham    56
Name: Quiz_1, dtype: int64

In [54]:
df.Quiz_1

Ram        78
Ravi       67
Shubham    56
Name: Quiz_1, dtype: int64

In [55]:
df.iloc[:,0]

Ram        78
Ravi       67
Shubham    56
Name: Quiz_1, dtype: int64

In [56]:
df.iloc[0:2,0]

Ram     78
Ravi    67
Name: Quiz_1, dtype: int64

**DATAFRAME WITHIN DATAFRAME**

In [57]:
rows=['Ram','Shubham']
cols =['Quiz_1','Quiz_3']
df_2 =df.loc[rows,cols]
df_2

Quiz_1  Quiz_3
Ram          78      89
Shubham      56      89

In [59]:
df.iloc[[0,2],[0,2]]

Quiz_1  Quiz_3
Ram          78      89
Shubham      56      89

In [60]:
df.iloc[[0,1,2],[0,1,2]]

Quiz_1  Quiz_2  Quiz_3
Ram          78      76      89
Ravi         67      87      65
Shubham      56      98      89

In [61]:
df['Quiz_avg']= df.mean(axis=1)
df

Quiz_1  Quiz_2  Quiz_3  Quiz_avg
Ram          78      76      89      81.0
Ravi         67      87      65      73.0
Shubham      56      98      89      81.0

In [62]:
df['Quiz_4']=[56,76,99]
df

Quiz_1  Quiz_2  Quiz_3  Quiz_avg  Quiz_4
Ram          78      76      89      81.0      56
Ravi         67      87      65      73.0      76
Shubham      56      98      89      81.0      99

In [63]:
del df['Quiz_avg']
df

Quiz_1  Quiz_2  Quiz_3  Quiz_4
Ram          78      76      89      56
Ravi         67      87      65      76
Shubham      56      98      89      99

In [64]:
df['Quiz_avg']= df.mean(axis=1)
df

Quiz_1  Quiz_2  Quiz_3  Quiz_4  Quiz_avg
Ram          78      76      89      56     74.75
Ravi         67      87      65      76     73.75
Shubham      56      98      89      99     85.50

In [65]:
import numpy as np
df_new =pd.DataFrame({'Quiz_1':[np.NaN],'Quiz_2':[np.NaN],'quiz_3':[np.NaN],'Quiz_4':[73]},index=['Adrian'])
df_new

Quiz_1  Quiz_2  quiz_3  Quiz_4
Adrian     NaN     NaN     NaN      73

In [66]:
df=pd.concat([df,df_new])
df

Quiz_1  Quiz_2  Quiz_3  Quiz_4  Quiz_avg  quiz_3
Ram        78.0    76.0    89.0      56     74.75     NaN
Ravi       67.0    87.0    65.0      76     73.75     NaN
Shubham    56.0    98.0    89.0      99     85.50     NaN
Adrian      NaN     NaN     NaN      73       NaN     NaN

In [67]:
df.mean(axis=1)

Ram        74.75
Ravi       73.75
Shubham    85.50
Adrian     73.00
dtype: float64

In [68]:
df.mean(axis=1,skipna=False)

Ram       NaN
Ravi      NaN
Shubham   NaN
Adrian    NaN
dtype: float64

In [69]:
df['Quiz_avg']=df.mean(axis=1,skipna=True)
df

Quiz_1  Quiz_2  Quiz_3  Quiz_4  Quiz_avg  quiz_3
Ram        78.0    76.0    89.0      56     74.75     NaN
Ravi       67.0    87.0    65.0      76     73.75     NaN
Shubham    56.0    98.0    89.0      99     85.50     NaN
Adrian      NaN     NaN     NaN      73     73.00     NaN

In [78]:
df['Quiz_4']=df['Quiz_4'].astype(float)
df

Quiz_1  Quiz_2  Quiz_4  quiz_3
Ram        78.0    76.0    56.0     NaN
Ravi       67.0    87.0    76.0     NaN
Shubham    56.0    98.0    99.0     NaN
Adrian      NaN     NaN    73.0     NaN

In [80]:
df['Quiz_5']=[45,67,76,78]
df

Quiz_1  Quiz_2  Quiz_4  quiz_3  Quiz_5
Ram        78.0    76.0    56.0     NaN      45
Ravi       67.0    87.0    76.0     NaN      67
Shubham    56.0    98.0    99.0     NaN      76
Adrian      NaN     NaN    73.0     NaN      78

In [82]:
df['Quiz_avg']= df.mean(axis=1)
df

Quiz_1  Quiz_2  Quiz_4  quiz_3  Quiz_5  Quiz_avg
Ram        78.0    76.0    56.0     NaN      45     63.75
Ravi       67.0    87.0    76.0     NaN      67     74.25
Shubham    56.0    98.0    99.0     NaN      76     82.25
Adrian      NaN     NaN    73.0     NaN      78     75.50

**WEATHER DATASET**

In [83]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My Drive/Colab Notebooks/
df =pd.read_csv("weather.csv")
df

Mounted at /content/drive
/content/drive/My Drive/Colab Notebooks


DAY  TEMPERATURE  WINDSPEED  EVENT
0  1/1/2017           32          6   RAIN
1  1/2/2017           35          7  SUNNY
2  1/3/2017           28          2   SNOW
3  1/4/2017           24          7   SNOW
4  1/5/2017           32          4   RAIN
5  1/6/2017           31          2  SUNNY

In [84]:
df.shape


(6, 4)

In [85]:
df.head()

DAY  TEMPERATURE  WINDSPEED  EVENT
0  1/1/2017           32          6   RAIN
1  1/2/2017           35          7  SUNNY
2  1/3/2017           28          2   SNOW
3  1/4/2017           24          7   SNOW
4  1/5/2017           32          4   RAIN

In [86]:
df.head(2)

DAY  TEMPERATURE  WINDSPEED  EVENT
0  1/1/2017           32          6   RAIN
1  1/2/2017           35          7  SUNNY

In [87]:
df.tail()

DAY  TEMPERATURE  WINDSPEED  EVENT
1  1/2/2017           35          7  SUNNY
2  1/3/2017           28          2   SNOW
3  1/4/2017           24          7   SNOW
4  1/5/2017           32          4   RAIN
5  1/6/2017           31          2  SUNNY

In [88]:
df.tail(3)

DAY  TEMPERATURE  WINDSPEED  EVENT
3  1/4/2017           24          7   SNOW
4  1/5/2017           32          4   RAIN
5  1/6/2017           31          2  SUNNY

In [89]:
df[2:5]

DAY  TEMPERATURE  WINDSPEED EVENT
2  1/3/2017           28          2  SNOW
3  1/4/2017           24          7  SNOW
4  1/5/2017           32          4  RAIN

In [90]:
df.columns

Index(['DAY', 'TEMPERATURE', 'WINDSPEED', 'EVENT'], dtype='object')

In [92]:
df.DAY

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: DAY, dtype: object

In [93]:
df.TEMPERATURE

0    32
1    35
2    28
3    24
4    32
5    31
Name: TEMPERATURE, dtype: int64

In [95]:
df[['DAY','EVENT']]

DAY  EVENT
0  1/1/2017   RAIN
1  1/2/2017  SUNNY
2  1/3/2017   SNOW
3  1/4/2017   SNOW
4  1/5/2017   RAIN
5  1/6/2017  SUNNY

In [96]:
df['TEMPERATURE'].max()

35

In [97]:
df['TEMPERATURE'].min()

24

In [100]:
df[df['EVENT']=='RAIN']

DAY  TEMPERATURE  WINDSPEED EVENT
0  1/1/2017           32          6  RAIN
4  1/5/2017           32          4  RAIN